datasets:
  iconqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/themes.json
        val:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/themes.json
        test:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/themes.json
      images:
        storage: /scratch/sg7484/ra/data/LAVIS/iconqa_data/iconqa 
        train:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/image
        val:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/image
        test:
          storage: /scratch/sg7484/ra/data/dataset/RSICap_split/image
          